AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
    - 'lib/yaml/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.1

# Preferred codebase style ---------------------------------------------
Layout/ExtraSpacing:
  AllowForAlignment: true

Style/FormatString:
  EnforcedStyle: percent

Style/AndOr:
  EnforcedStyle: conditionals

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/EmptyElse:
  EnforcedStyle: empty

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 300

Metrics/ParameterLists:
  Max: 15

Style/ParallelAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FileName:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# Current preferred metrics --------------------------------------------
# Better values are encouraged, but not required.
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8  

Metrics/PerceivedComplexity:
  Max: 8

# TODO -----------------------------------------------------------------

Style/Documentation:
  Enabled: false
